import os
import time

def count(filename): #counts the number of lines
	try:
		f = open(filename,'r') #reads the file
		count = 0 
		for line in f: #read until end of file
			count+=1
		f.close()
		return count #number 
	except:
		return 0 #returns 0 if file does not exist

while(1):
	for i in range(0,10): #readeach file generated by filter.py
		print 'File '+str(i)+':'+str(count(str(i)+'.txt'))
	time.sleep(1) #gives a sec delay qn said so..
	print '**************'

