#!/usr/bin/python
#sorter.py
#renjithforever@gmail.com
"""
mobme codejam : Ternery
-------------------------
SORTER(consumer):

Accepts numbers generated by `producer`, sorts and writes those to respective files.
"""

import socket
import sys
import time
if __name__=='__main__':
	try:
		client_socket=socket.socket(socket.AF_INET,socket.SOCK_STREAM)
		client_socket.connect(("localhost",4444))
	except socket.error, (value,message):
		sys.exit("could not open socket:"+message+"\npls run Producer first")
	print "\n_____________________________________"
	print "Connected to Producer.\nWill display numbers tranferred from Producer.\nNumbers will be sorted and written to files."
	print "Start transferring in..10 seconds."
	time.sleep(10)

	file=[]

	for i in range(10):
		filename=str(i)+'.txt'
		file.append(open(filename,"w"))			#file objects are put in a list.

	while True:
		number=client_socket.recv(1024)
		if number=='':
			break
		print number
		number+='\n'
		file[int(number[0])].write(number)		#handles all the respective files.
		client_socket.send('ACK')

	client_socket.close()
